server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/country?serverTimezone=Asia/Shanghai
    username: hgc
    password: Hh209694
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: Hh209694
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 0
logging:
  config: classpath:log4j2-pro.xml